### ISSUE TITLE
Relationship between book and series

### ISSUE THREAD

**Issue by arwhyte** [ssciolla/si664-asian-studies-books#1]
You write:

> I was a bit uncertain how to handle the relationship between books and series; I decided to create an intermediate table called series_membership between them, since the volume number did not seem to fit (be fully dependent on) either the series or book entity.

I think that the relationship between `book` and `series` is 1:M.  If true, then I would add both `series_id` (FK) and `volume` to `book`.

**Comment by ssciolla** [comment]
I believe this has been addressed. Take a look at the latest data model in README.md.
